### ISSUE TITLE
Remove code duplication in allergies/allergies.py

### ISSUE THREAD

**Issue by virtuallight** [zarniak/exercism.io#18]
There is code duplication: https://github.com/zarniak/exercism.io/blob/7c3156326c3e28b4c6c49d8c9191f14aac218348/allergies/allergies.py#L21-L28 and https://github.com/zarniak/exercism.io/blob/7c3156326c3e28b4c6c49d8c9191f14aac218348/allergies/allergies.py#L34-L41.

`self.allergen_list` already holds the computed list of allergens, as of https://github.com/zarniak/exercism.io/blob/7c3156326c3e28b4c6c49d8c9191f14aac218348/allergies/allergies.py#L17. How about simply checking if the `item` is in `self.allergen_list` in https://github.com/zarniak/exercism.io/blob/7c3156326c3e28b4c6c49d8c9191f14aac218348/allergies/allergies.py#L31?

**Comment by zarniak** [comment]
@virtuallight 

if i change whole "is_allergic_to" to:

```
    def is_allergic_to(self, item):
        return item in self.allergen_list
```

i get an error

```
.E......E.E.E
======================================================================
ERROR: test_allergic_to_eggs_in_addition_to_other_stuff (__main__.AllergiesTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/main.py", line 24, in test_allergic_to_eggs_in_addition_to_other_stuff
    self.assertIs(allergies.is_allergic_to('eggs'), True)
  File "/home/allergies.py", line 32, in is_allergic_to
    return item in self.allergen_list
TypeError: argument of type 'method' is not iterable

======================================================================
ERROR: test_allergic_to_strawberries_but_not_peanuts (__main__.AllergiesTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/main.py", line 30, in test_allergic_to_strawberries_but_not_peanuts
    self.assertIs(allergies.is_allergic_to('eggs'), True)
  File "/home/allergies.py", line 32, in is_allergic_to
    return item in self.allergen_list
TypeError: argument of type 'method' is not iterable

======================================================================
ERROR: test_is_allergic_to_eggs (__main__.AllergiesTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/main.py", line 20, in test_is_allergic_to_eggs
    self.assertIs(Allergies(1).is_allergic_to('eggs'), True)
  File "/home/allergies.py", line 32, in is_allergic_to
    return item in self.allergen_list
TypeError: argument of type 'method' is not iterable

======================================================================
ERROR: test_no_allergies_means_not_allergic (__main__.AllergiesTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/main.py", line 15, in test_no_allergies_means_not_allergic
    self.assertIs(allergies.is_allergic_to('peanuts'), False)
  File "/home/allergies.py", line 32, in is_allergic_to
    return item in self.allergen_list
TypeError: argument of type 'method' is not iterable

----------------------------------------------------------------------
Ran 13 tests in 0.008s

FAILED (errors=4)
```

**Comment by virtuallight** [comment]
@zarniak This issue has the same root as #19. Please have a look at https://github.com/zarniak/exercism.io/issues/19#issuecomment-453620702.
